# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/maven-course',
                'doc_host': 'https://deven367.github.io',
                'git_url': 'https://github.com/deven367/maven-course',
                'lib_path': 'maven_course'},
  'syms': {'maven_course.core': {'maven_course.core.foo': ('core.html#foo', 'maven_course/core.py')}}}
